import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ThemeChanger from "../components/ThemeChanger";
import TestPage from "./TestPage";
import Dashboard from "./dashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Serpsploit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <TestPage /> */}
      <Dashboard />
    </>
  );
}
